services:
  llm-service:
    image: hotel-vllm-grpc:0.1.0
    build:
      context: .
      dockerfile: Dockerfile.grpc
    ports:
      - "127.0.0.1:15051:50051"
    gpus: all
    ipc: host
    environment:
      HF_TOKEN: ${HF_TOKEN}
    volumes:
      - hf-cache:/root/.cache/huggingface
    networks:
      model-network:
      backend-network:
        aliases:
          - llm-service
  fastapi-app:
    build: .
    ports:
      - "9001:9000"
    env_file:
      - .env
    depends_on:
      - llm-service

volumes:
  hf-cache:

networks:
  model-network:
    name: vllm-model-network
  backend-network:
    external: true
    name: fastapi-backend_default